addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.32"
  - "5.32-thr"
  - "5.30"
  - "5.30-thr"
  - "5.28"
  - "5.28-thr"
  - "5.26"
  - "5.26-thr"
  - "5.24"
  - "5.24-thr"
  - "5.22"
  - "5.22-thr"
  - "5.20"
  - "5.20-thr"
  - "5.18"
  - "5.18-thr"
  - "5.16"
  - "5.16-thr"
  - "5.14"
  - "5.14-thr"
  - "5.12"
  - "5.12-thr"
  - "5.10"
  - "5.10-thr"
  - blead       # builds perl from git
  - blead-thr
  - dev         # latest point release
  - dev-thr
matrix:
  include:
    # Hash::Util::FieldHash not available on 5.8: required for compile test of ::PP::FieldHash
    - perl: "5.8.0"
      env: AUTHOR_TESTING=0
    - perl: "5.8.0-thr"
      env: AUTHOR_TESTING=0
    - perl: "5.8.4"
      env: AUTHOR_TESTING=0
    - perl: "5.8.4-thr"
      env: AUTHOR_TESTING=0
    - perl: "5.8.8"
      env: AUTHOR_TESTING=0
    - perl: "5.8.8-thr"
      env: AUTHOR_TESTING=0
    # modules required for author testing do not build on 5.6
    - perl: "5.6.2"
      env: AUTHOR_TESTING=0
    - perl: "5.6.2-thr"
      env: AUTHOR_TESTING=0
  allow_failures:
    - perl: "5.6.2"
    - perl: "5.6.2-thr"
  fast_finish: 1
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
